version: "3.8"
services:
  dbserver:
    image: mysql:5.7
    container_name: dbserver
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - server
      - database-admin
    volumes:
      - dbserver_volume:/var/lib/mysql/

  server:
    build: ./server
    container_name: server
    depends_on:
      - dbserver
    networks:
      - internal
      - server
    deploy:
      restart_policy:
        condition: on-failure

  dbauth:
    image: mysql:5.7
    container_name: dbauth
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - auth
      - database-admin
    volumes:
      - dbauth_volume:/var/lib/mysql/

  auth:
    build: ./auth
    container_name: auth
    depends_on:
      - dbauth
      - server
    networks:
      - internal
      - auth
    deploy:
      restart_policy:
        condition: on-failure

  kong:
    image: kong:latest
    volumes:
      - ./kong:/usr/local/kong/declarative
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - 8001:8000
      - 8002:8443
    networks:
      - internal
    deploy:
      placement:
        constraints: [node.role == manager]

  adminer:
    image: adminer
    networks:
      - database-admin
      - internal

networks:
  internal:
  server:
  auth:
  database-admin:

volumes:
  dbauth_volume: {}
  dbserver_volume: {}
