version: "3.7"
services:

  dbserver:
    image: mysql:5.7
    hostname: dbserver
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbserver_volume:/var/lib/mysql/

  server:
    image: shinr3x/figaro:server
    hostname: server
    ports:
      - 5001:5000
    depends_on:
      - dbserver
    deploy:
      restart_policy:
        condition: on-failure

  dbauth:
    image: mysql:5.7
    hostname: dbauth
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbauth_volume:/var/lib/mysql/
    
  auth:
    image: shinr3x/figaro:auth
    hostname: auth
    ports:
      - 5000:5000
    depends_on:
      - dbauth
      - server
    deploy:
      restart_policy:
        condition: on-failure

  metrics:
    image: prom/prometheus:latest
    hostname: metrics
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_volume:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    depends_on:
      - auth


volumes:
  dbauth_volume: {}
  dbserver_volume: {}
  prometheus_volume: {}