version: "3.7"
services:
  dbserver:
    image: mysql:5.7
    container_name: dbserver
    environment:
      MYSQL_ROOT_PASSWORD: root

  server:
    image: shinr3x/figaro:server
    container_name: server
    ports:
      - 5001:5000
    depends_on:
      - dbserver

  dbauth:
    image: mysql:5.7
    container_name: dbauth
    environment:
      MYSQL_ROOT_PASSWORD: root

  auth:
    image: shinr3x/figaro:auth
    container_name: auth
    ports:
      - 5000:5000
    depends_on:
      - dbauth
      - server

  metrics:
    image: prom/prometheus:latest
    container_name: metrics
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    ports:
      - 9090:9090
    depends_on:
      - auth
